### ISSUE TITLE
Long names ruin appearance of selected spot

### ISSUE THREAD

**Issue by nickatomlin** [nickatomlin/Parks#19]
In particular, the eight results for "Fred Lippitt Woonasquatucket River Greenway" take up three lines in the selected spot column. Consider changing the text size, the park name, or the space allowed for the name.

**Comment by Designist** [comment]
![three-lines](https://cloud.githubusercontent.com/assets/13228316/16347310/046d2d98-3a1a-11e6-96f1-f35f21af841e.PNG)

**Comment by nickatomlin** [comment]
Fixed by 4269b5ec71df9c012bec33fc0fca66eb6ce6e085
