### ISSUE TITLE
Add google maps directions link

### ISSUE THREAD

**Issue by nickatomlin** [nickatomlin/Parks#27]
Instead of just linking to the location on Google Maps, link to the directions from the input location to the park. Should optionally link to the old version, in case the user doesn't provide location.

**Comment by nickatomlin** [comment]
This has proven difficult because we only have access to the place location in HTML, so forming a URL concatenated with the user location is difficult.

**Comment by theryankelly** [comment]
Get Direction link from GetOutdoorsRI Drupal instance: https://www.google.com/maps/dir/Current+Location/41.830008000000,-71.410546000000

**Comment by nickatomlin** [comment]
Added as of cf6b04e057d7af6e9cad527848d052e8887b0724 using the method @theryankelly suggested.
