### ISSUE TITLE
Map not full width on tablet, phone landscape mode, etc.

### ISSUE THREAD

**Issue by nickatomlin** [nickatomlin/Parks#35]
The header and footer are meant to disappear when the width is less than 1024px. This works as expected on Safari, Chrome for Mac, and iOS 9/10 on iPads and iPhones. It does not work on Firefox for Mac, or any windows browser.

However, when this re-sizing happens, the map and selected spot no longer sit side-by-side. This creates a huge, unwanted margin around the map, as seen below.
<img width="955" alt="screen shot 2016-06-28 at 9 19 07 am" src="https://cloud.githubusercontent.com/assets/13228316/16416683/6ec72da2-3d11-11e6-92e8-c09727f39b12.png">

**Comment by Designist** [comment]
Consider: https://responsivedesign.is/develop/browser-feature-support/media-queries-for-common-device-breakpoints

**Comment by nickatomlin** [comment]
Fixed as of ef8326c558ef9fd60a56efed8fb7daf2177b3bcd by removing `max-width: 460px;` and `margin: 0px auto;` from the wrapper.
