### ISSUE TITLE
Mobile compatibility

### ISSUE THREAD

**Issue by nickatomlin** [nickatomlin/Parks#37]
Add mobile compatibility for different device types, including phones/tablets in landscape and portrait mode. See here: https://responsivedesign.is/develop/browser-feature-support/media-queries-for-common-device-breakpoints

**Comment by nickatomlin** [comment]
Full mobile functionality as of 11f39d3c1a5f5583ce48540c872d8650efe95d3e. Adding device-specific CSS is the only remaining task here.

**Comment by nickatomlin** [comment]
**Tablet Landscape** full functionality.

**Tablet Portrait** no footer.

**Phone** no header, text-only footer, single column view.

**Comment by nickatomlin** [comment]
Stylish as of 26393739b7a235594c683de2111d8a53b353497c.

**Comment by theryankelly** [comment]
Samsung Galaxy Note5 : Chrome 51.0.2704.81
![screenshot_20160718-093543](https://cloud.githubusercontent.com/assets/2421382/16919659/a33c149a-4cd8-11e6-9256-6a21ee9104a5.png)

**Comment by nickatomlin** [comment]
Verified working on Shawn's phone as of 1f50039161bfd48a9d9974be6d3dfb9b7e79c35b. Not a Galaxy, though, so this could potentially be a Samsung-specific issue.

Also, I contacted a cross-browser compatibility testing suite provider about getting a free license because all of our code is publicly available.

**Comment by nickatomlin** [comment]
Fixed as of f0dea657c755b0298232e83de1d11e5f28242308.
