### ISSUE TITLE
Add "miles away" text on latest/selected spots

### ISSUE THREAD

**Issue by nickatomlin** [nickatomlin/Parks#38]
The "___ Miles Away" text under the latest/selected spots' city names was removed when fixing #4. One obvious solution here would be to create a `<p id="milesAway" class="colorText"></p>` and use `document.getElementById("milesAway").innerHTML` to set the value in JS. However, this does not work because the latest/selected spots are handled by text/html scripts.

**Comment by theryankelly** [comment]
@Designist can you describe the use case when this does not work properly?

**Comment by nickatomlin** [comment]
Fixed in all cases as of a8693c8aee99745581a1f95cb8ca2e68723743a2
