### ISSUE TITLE
Header and Footer Design

### ISSUE THREAD

**Issue by theryankelly** [nickatomlin/Parks#47]
Mock up potential options global header and footer

**Comment by theryankelly** [comment]
Mock up of drop shadow idea in header ![about_dropshadow](https://cloud.githubusercontent.com/assets/2421382/16591664/eaf919c8-42aa-11e6-9b0b-1dcc13e28c33.jpg)

**Comment by bmcguirk** [comment]
Tools: 
- [Great overview article](http://www.techradar.com/us/news/software/applications/best-free-photo-editing-software-10-top-image-editors-you-should-try-1135489)
- [Pixlr](https://pixlr.com) - from AutoDesk. Pretty legit free version. Web-based or desktop. Trying this right now.
- More to come.

**Comment by bmcguirk** [comment]
![image](https://cloud.githubusercontent.com/assets/7449705/16592103/1d4ac8d4-42ad-11e6-8837-5d77ee24fdd8.png)
Quick shot of a color overlay via Pixlr. This took two seconds.

**Comment by bmcguirk** [comment]
Less good for net-new Fireworks/Photoshop style asset creation.

**Comment by bmcguirk** [comment]
@theryankelly Inkscape (same people as GIMP) looks pretty good for vector graphics, and not as hideous as GIMP.

**Comment by theryankelly** [comment]
Quick mock up of an "included" footer that has any combination of links within our park landscape.
![bottom footer](https://cloud.githubusercontent.com/assets/2421382/16594267/9fe4db68-42b7-11e6-8ee2-699e7cd975ee.jpg)

**Comment by nickatomlin** [comment]
Love the footer look! Seems like it might be a bit difficult to implement effectively, but if we can do it that would be great.

Edit: the footer has been implemented with the major exception of the partner slider.

**Comment by nickatomlin** [comment]
The header and footer designs have been effectively implemented as of 005de7137af82a81a54af58c33c7728b15c420a0. Not expecting any major changes until logo/color scheme changes.
<img width="1245" alt="screen shot 2016-07-08 at 10 23 09 am" src="https://cloud.githubusercontent.com/assets/13228316/16691472/cb3e9020-44fa-11e6-8578-3d699202d309.png">
