### ISSUE TITLE
Add street type to the data

### ISSUE THREAD

**Issue by theryankelly** [nickatomlin/Parks#48]
Reverse geocode with Mapquest gave 2/3 of the matching streets.  

Near streets feature could be used in Arc Map

**Comment by nickatomlin** [comment]
This now involves moving data in the SCORP_GEO_Filtered.xlsx to the Master SCORP and has been documented [here](https://github.com/401ode/RI-Recreational-Areas/issues/3#issuecomment-234041896). @bmcguirk has it taken care of, I believe.
