### ISSUE TITLE
Add about section to homepage

### ISSUE THREAD

**Issue by theryankelly** [nickatomlin/Parks#50]
Integrate with design of header and footer #47

Draft About Text:  "GetOutdoorsRI looks to promote the use of Rhode Island's public outdoor resources and increase public engagement.  Use the table and map to find a public place to explore!

Rhode Island has [390] outdoors recreation areas with Running, Walking, Hiking, Swimming, Biking, Paddling activities listed on this site.  Find even more public assets here [https://github.com/401ode/RI-Recreational-Areas].  Contribute [https://github.com/401ode/GetOutdoorsRI] and help us enable more features like badges, blogs and events."

**Comment by nickatomlin** [comment]
I feel like we should make the About text more user-friendly if we're advertising this site to the general public. Phrases like "public assets" and "increase public engagement" are jargon-y and unnecessary for the casual user. Any thoughts?

**Comment by nickatomlin** [comment]
2e936a6a4de667e25f09b54ce349359160051d34
