### ISSUE TITLE
Fix Vagrant issues

### ISSUE THREAD

**Issue by nickatomlin** [nickatomlin/Parks#53]
Vagrant has gone rogue and cannot be deleted.

**Comment by nickatomlin** [comment]
`sendfile off; # Per https://www.vagrantup.com/docs/synced-folders/virtualbox.html`

Source: http://stackoverflow.com/questions/20997984/vagrant-wont-start-on-windows-cmd-errnoeacces

**Comment by bmcguirk** [comment]
Fixed. And proud of it.
