### ISSUE TITLE
Slider Display Issues

### ISSUE THREAD

**Issue by theryankelly** [nickatomlin/Parks#59]
Slider does not always display.  Appeared to not display if Explore page was loaded first.  Going to About then back to Explore made the slider images appear.

Missing:
![capture7_8_2016](https://cloud.githubusercontent.com/assets/2421382/16700995/2f2485c4-452b-11e6-98e1-be47b161b16c.PNG)

**Comment by nickatomlin** [comment]
Managed to duplicate this on first load of the Explore page on my laptop. Refreshing the page made the slider appear. I'm guessing the jCarouselLite script isn't loading in time or something?

Edit: ignore that. Now it's often happening that the upper half of an image loads but not the lower half.

![broken-slider](https://cloud.githubusercontent.com/assets/13228316/16731893/7b2f1e56-4748-11e6-83ce-7995ad755f7f.PNG)
_in the image above, the slider still works but the logos cannot be seen properly_

**Comment by nickatomlin** [comment]
Fixed as of affc4d0f14a44d6539cfed662c3320c61dd50de2 by fixing the height of slider list elements.
