### ISSUE TITLE
Compatibility with IE 10

### ISSUE THREAD

**Issue by nickatomlin** [nickatomlin/Parks#73]
The social media share div has compatibility issues with IE 10, as shown in the below screenshot. This may be related to flexbox issues since the website appears similar to one in Chrome/IE 11 without flexbox display enabled.
![image001](https://cloud.githubusercontent.com/assets/13228316/16959416/04a74724-4db3-11e6-8630-fc9540cd9b64.png)

**Comment by nickatomlin** [comment]
Attempted fix in b6cc189cfdd68460c893942af22ada9955a8e58f. Edit: fix worked for about page/social but not for the footer.
![ie10](https://cloud.githubusercontent.com/assets/13228316/17025816/9f705de4-4f2b-11e6-8329-5110ae314018.png)

**Comment by nickatomlin** [comment]
**With only 2-3% of people still using IE 10** as their primary browser, we've decided to drop IE 10 support for this site. While the site will still be _usable_ in IE 10, it lacks key functionality, such as location updating and a working footer. Various styling throughout the site is also missing or significantly altered on IE 10.

Check out [caniuse.com](http://caniuse.com/#feat=flexbox) for some information about IE 10's compatibility with modern HTML and CSS.

**Comment by bmcguirk** [comment]
@Designist - Worth a warning message of some kind to the user? Links to Chrome and Firefox? :)

**Comment by nickatomlin** [comment]
@bmcguirk Used Modernizr to add alert for browsers that don't support Flexbox in 731ff38baf1f08af4c794661f58807e9699c9f11.

**Comment by bmcguirk** [comment]
@Designist You're a smart kid. :+1:

**Comment by nickatomlin** [comment]
<img width="1218" alt="screen shot 2016-07-21 at 11 30 34 am" src="https://cloud.githubusercontent.com/assets/13228316/17028781/98191530-4f36-11e6-9e98-49df5bd8f727.png">
